slam_toolbox:
  ros__parameters:
    ################## TEMPS ##################
    use_sim_time: false

    ################## FRAMES #################
    map_frame: map          # frame de la carte
    odom_frame: odom        # frame intermédiaire
    base_frame: base_link   # frame du robot
    scan_topic: /scan       # topic du LIDAR

    ############# ODOM / TRANSFORMS ###########
    use_odometry: false         # PAS d'odom externe
    provide_odom_frame: true    # slam_toolbox gère map->odom
    use_tf_scan_transformation: true
    use_scan_matching: true
    debug_logging: false
    publish_tf: true

    tf_buffer_duration: 30.0
    transform_timeout: 0.5
    transform_publish_period: 0.02
    map_update_interval: 2.0

    ############## LIDAR / FILTRES ############
    throttle_scans: 1
    minimum_travel_distance: 0.01
    minimum_travel_heading: 0.01

    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 15.0
    max_laser_range: 15.0

    ############## CARTE ######################
    resolution: 0.05        # 5 cm
    mode: "mapping"         # SLAM online

    ############## SOLVER CERES ###############
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    ############## DIVERS #####################
    enable_interactive_mode: true
